# Generated by Django 4.1 on 2022-08-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_id', models.CharField(max_length=255, unique=True)),
                ('checkin', models.DateTimeField(verbose_name='Check in time')),
                ('checkout', models.DateTimeField(null=True, verbose_name='Check out time')),
                ('rental_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.rental')),
            ],
        ),
    ]
